// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: yrpc.proto

/*
	Package yrpc is a generated protocol buffer package.

	It is generated from these files:
		yrpc.proto

	It has these top-level messages:
		Ypacket
		Yempty
		Ynocare
		UnixTime
		NatsOption
*/
package yrpc

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// 系统中所有的消息交互底层都以此为包装,这是yrpc中的最小交互数据包
type Ypacket struct {
	// 整个yrpc packet的长度，不包含此字段
	// 虽然这个长度可以很长，但是为了避免大包阻塞其它操作，通常都要限制长度,采用分包多发机制
	// 当使用基于包的传输通道时(udp/kcp/websocket)，此值可能为0(此时长度为收到的整个包的长度)
	// 当填写了值时,为proto编码的长度-5
	Len uint32 `protobuf:"fixed32,1,opt,name=len,proto3" json:"len,omitempty"`
	// rpc command,rpc的命令和option
	// b15-b0(uint16):为rpc命令
	// b17-b16:body压缩方式 0:无压缩 1:lz4 2:zlib inflate/deflate
	// b19-b18:optbin压缩方式 0:无压缩 1:lz4 2:zlib inflate/deflate
	// b31-b20: not used yet
	Cmd uint32 `protobuf:"fixed32,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// rpc call id,给分辨不同的rpc调用使用,调用方增1循环使用
	Cid uint32 `protobuf:"varint,3,opt,name=cid,proto3" json:"cid,omitempty"`
	// rpc no,从0开始增1使用,用于区分收到重复的包,特别是udp的情况下
	// 每一个rpc 流式调用有其自己的序号流,从0开始
	No uint32 `protobuf:"varint,4,opt,name=no,proto3" json:"no,omitempty"`
	// response code
	Res int32 `protobuf:"zigzag32,5,opt,name=res,proto3" json:"res,omitempty"`
	// packet body
	Body []byte `protobuf:"bytes,10,opt,name=body,proto3" json:"body,omitempty"`
	// optional str parameter,额外的信息,一般不会有,有些特殊命令里面可能用到
	Optstr string `protobuf:"bytes,11,opt,name=optstr,proto3" json:"optstr,omitempty"`
	// optional binary parameter,额外的信息,一般不会有,有些特殊命令里面可能用到
	Optbin []byte `protobuf:"bytes,12,opt,name=optbin,proto3" json:"optbin,omitempty"`
	// optional meta info,key=meta[i],value=meta[i+1]
	Meta []string `protobuf:"bytes,13,rep,name=meta" json:"meta,omitempty"`
}

func (m *Ypacket) Reset()                    { *m = Ypacket{} }
func (m *Ypacket) String() string            { return proto.CompactTextString(m) }
func (*Ypacket) ProtoMessage()               {}
func (*Ypacket) Descriptor() ([]byte, []int) { return fileDescriptorYrpc, []int{0} }

func (m *Ypacket) GetLen() uint32 {
	if m != nil {
		return m.Len
	}
	return 0
}

func (m *Ypacket) GetCmd() uint32 {
	if m != nil {
		return m.Cmd
	}
	return 0
}

func (m *Ypacket) GetCid() uint32 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *Ypacket) GetNo() uint32 {
	if m != nil {
		return m.No
	}
	return 0
}

func (m *Ypacket) GetRes() int32 {
	if m != nil {
		return m.Res
	}
	return 0
}

func (m *Ypacket) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Ypacket) GetOptstr() string {
	if m != nil {
		return m.Optstr
	}
	return ""
}

func (m *Ypacket) GetOptbin() []byte {
	if m != nil {
		return m.Optbin
	}
	return nil
}

func (m *Ypacket) GetMeta() []string {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Yempty struct {
}

func (m *Yempty) Reset()                    { *m = Yempty{} }
func (m *Yempty) String() string            { return proto.CompactTextString(m) }
func (*Yempty) ProtoMessage()               {}
func (*Yempty) Descriptor() ([]byte, []int) { return fileDescriptorYrpc, []int{1} }

// A generic nocare message that you can use to info the call is not important and no care the result.
// A typical example is to use it in report log/trace. For instance:
//
//     service Log {
//       rpc Log(infos) returns (yrpc.Ynocare);
//     }
//
type Ynocare struct {
}

func (m *Ynocare) Reset()                    { *m = Ynocare{} }
func (m *Ynocare) String() string            { return proto.CompactTextString(m) }
func (*Ynocare) ProtoMessage()               {}
func (*Ynocare) Descriptor() ([]byte, []int) { return fileDescriptorYrpc, []int{2} }

type UnixTime struct {
	// Unix time, the number of miliseconds elapsed since January 1, 1970 UTC
	TimeUnix int64 `protobuf:"zigzag64,1,opt,name=time_unix,json=timeUnix,proto3" json:"time_unix,omitempty"`
	// utc time yyyy-MM-dd hh:mm:ss.zzz
	TimeStr string `protobuf:"bytes,2,opt,name=time_str,json=timeStr,proto3" json:"time_str,omitempty"`
}

func (m *UnixTime) Reset()                    { *m = UnixTime{} }
func (m *UnixTime) String() string            { return proto.CompactTextString(m) }
func (*UnixTime) ProtoMessage()               {}
func (*UnixTime) Descriptor() ([]byte, []int) { return fileDescriptorYrpc, []int{3} }

func (m *UnixTime) GetTimeUnix() int64 {
	if m != nil {
		return m.TimeUnix
	}
	return 0
}

func (m *UnixTime) GetTimeStr() string {
	if m != nil {
		return m.TimeStr
	}
	return ""
}

type NatsOption struct {
	// original sid
	OrigSid []byte `protobuf:"bytes,1,opt,name=orig_sid,json=origSid,proto3" json:"orig_sid,omitempty"`
	// original cid
	OrigCid uint32 `protobuf:"varint,2,opt,name=orig_cid,json=origCid,proto3" json:"orig_cid,omitempty"`
	// nats replay
	Reply string `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
	// optional binary parameters
	Obin []byte `protobuf:"bytes,4,opt,name=obin,proto3" json:"obin,omitempty"`
}

func (m *NatsOption) Reset()                    { *m = NatsOption{} }
func (m *NatsOption) String() string            { return proto.CompactTextString(m) }
func (*NatsOption) ProtoMessage()               {}
func (*NatsOption) Descriptor() ([]byte, []int) { return fileDescriptorYrpc, []int{4} }

func (m *NatsOption) GetOrigSid() []byte {
	if m != nil {
		return m.OrigSid
	}
	return nil
}

func (m *NatsOption) GetOrigCid() uint32 {
	if m != nil {
		return m.OrigCid
	}
	return 0
}

func (m *NatsOption) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func (m *NatsOption) GetObin() []byte {
	if m != nil {
		return m.Obin
	}
	return nil
}

func init() {
	proto.RegisterType((*Ypacket)(nil), "yrpc.Ypacket")
	proto.RegisterType((*Yempty)(nil), "yrpc.Yempty")
	proto.RegisterType((*Ynocare)(nil), "yrpc.Ynocare")
	proto.RegisterType((*UnixTime)(nil), "yrpc.UnixTime")
	proto.RegisterType((*NatsOption)(nil), "yrpc.natsOption")
}
func (m *Ypacket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ypacket) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Len != 0 {
		dAtA[i] = 0xd
		i++
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(m.Len))
		i += 4
	}
	if m.Cmd != 0 {
		dAtA[i] = 0x15
		i++
		binary.LittleEndian.PutUint32(dAtA[i:], uint32(m.Cmd))
		i += 4
	}
	if m.Cid != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(m.Cid))
	}
	if m.No != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(m.No))
	}
	if m.Res != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintYrpc(dAtA, i, uint64((uint32(m.Res)<<1)^uint32((m.Res>>31))))
	}
	if len(m.Body) > 0 {
		dAtA[i] = 0x52
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(len(m.Body)))
		i += copy(dAtA[i:], m.Body)
	}
	if len(m.Optstr) > 0 {
		dAtA[i] = 0x5a
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(len(m.Optstr)))
		i += copy(dAtA[i:], m.Optstr)
	}
	if len(m.Optbin) > 0 {
		dAtA[i] = 0x62
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(len(m.Optbin)))
		i += copy(dAtA[i:], m.Optbin)
	}
	if len(m.Meta) > 0 {
		for _, s := range m.Meta {
			dAtA[i] = 0x6a
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *Yempty) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Yempty) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *Ynocare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Ynocare) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *UnixTime) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UnixTime) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TimeUnix != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintYrpc(dAtA, i, uint64((uint64(m.TimeUnix)<<1)^uint64((m.TimeUnix>>63))))
	}
	if len(m.TimeStr) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(len(m.TimeStr)))
		i += copy(dAtA[i:], m.TimeStr)
	}
	return i, nil
}

func (m *NatsOption) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NatsOption) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.OrigSid) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(len(m.OrigSid)))
		i += copy(dAtA[i:], m.OrigSid)
	}
	if m.OrigCid != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(m.OrigCid))
	}
	if len(m.Reply) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(len(m.Reply)))
		i += copy(dAtA[i:], m.Reply)
	}
	if len(m.Obin) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintYrpc(dAtA, i, uint64(len(m.Obin)))
		i += copy(dAtA[i:], m.Obin)
	}
	return i, nil
}

func encodeVarintYrpc(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Ypacket) Size() (n int) {
	var l int
	_ = l
	if m.Len != 0 {
		n += 5
	}
	if m.Cmd != 0 {
		n += 5
	}
	if m.Cid != 0 {
		n += 1 + sovYrpc(uint64(m.Cid))
	}
	if m.No != 0 {
		n += 1 + sovYrpc(uint64(m.No))
	}
	if m.Res != 0 {
		n += 1 + sozYrpc(uint64(m.Res))
	}
	l = len(m.Body)
	if l > 0 {
		n += 1 + l + sovYrpc(uint64(l))
	}
	l = len(m.Optstr)
	if l > 0 {
		n += 1 + l + sovYrpc(uint64(l))
	}
	l = len(m.Optbin)
	if l > 0 {
		n += 1 + l + sovYrpc(uint64(l))
	}
	if len(m.Meta) > 0 {
		for _, s := range m.Meta {
			l = len(s)
			n += 1 + l + sovYrpc(uint64(l))
		}
	}
	return n
}

func (m *Yempty) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *Ynocare) Size() (n int) {
	var l int
	_ = l
	return n
}

func (m *UnixTime) Size() (n int) {
	var l int
	_ = l
	if m.TimeUnix != 0 {
		n += 1 + sozYrpc(uint64(m.TimeUnix))
	}
	l = len(m.TimeStr)
	if l > 0 {
		n += 1 + l + sovYrpc(uint64(l))
	}
	return n
}

func (m *NatsOption) Size() (n int) {
	var l int
	_ = l
	l = len(m.OrigSid)
	if l > 0 {
		n += 1 + l + sovYrpc(uint64(l))
	}
	if m.OrigCid != 0 {
		n += 1 + sovYrpc(uint64(m.OrigCid))
	}
	l = len(m.Reply)
	if l > 0 {
		n += 1 + l + sovYrpc(uint64(l))
	}
	l = len(m.Obin)
	if l > 0 {
		n += 1 + l + sovYrpc(uint64(l))
	}
	return n
}

func sovYrpc(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozYrpc(x uint64) (n int) {
	return sovYrpc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Ypacket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ypacket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ypacket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Len", wireType)
			}
			m.Len = 0
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			m.Len = uint32(binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cmd", wireType)
			}
			m.Cmd = 0
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			m.Cmd = uint32(binary.LittleEndian.Uint32(dAtA[iNdEx:]))
			iNdEx += 4
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cid", wireType)
			}
			m.Cid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Cid |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field No", wireType)
			}
			m.No = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.No |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Res", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.Res = v
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthYrpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = append(m.Body[:0], dAtA[iNdEx:postIndex]...)
			if m.Body == nil {
				m.Body = []byte{}
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Optstr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Optstr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Optbin", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthYrpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Optbin = append(m.Optbin[:0], dAtA[iNdEx:postIndex]...)
			if m.Optbin == nil {
				m.Optbin = []byte{}
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Meta = append(m.Meta, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Yempty) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Yempty: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Yempty: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipYrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Ynocare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Ynocare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Ynocare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipYrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UnixTime) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UnixTime: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UnixTime: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeUnix", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.TimeUnix = int64(v)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeStr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TimeStr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NatsOption) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowYrpc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: natsOption: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: natsOption: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrigSid", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthYrpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrigSid = append(m.OrigSid[:0], dAtA[iNdEx:postIndex]...)
			if m.OrigSid == nil {
				m.OrigSid = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrigCid", wireType)
			}
			m.OrigCid = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrigCid |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reply", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthYrpc
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reply = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Obin", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthYrpc
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Obin = append(m.Obin[:0], dAtA[iNdEx:postIndex]...)
			if m.Obin == nil {
				m.Obin = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipYrpc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthYrpc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipYrpc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowYrpc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowYrpc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthYrpc
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowYrpc
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipYrpc(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthYrpc = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowYrpc   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("yrpc.proto", fileDescriptorYrpc) }

var fileDescriptorYrpc = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x7f, 0x27, 0x69, 0xd3, 0xcc, 0xdf, 0x22, 0xb0, 0x10, 0x32, 0x42, 0x8a, 0xa2, 0xac,
	0xb2, 0x62, 0xc3, 0x0d, 0xca, 0x86, 0x1d, 0x92, 0x0b, 0x8b, 0xae, 0xaa, 0x34, 0xb6, 0x90, 0x45,
	0x63, 0x5b, 0x8e, 0x91, 0x9a, 0x5b, 0x70, 0x1d, 0x6e, 0xc0, 0x92, 0x23, 0xa0, 0x72, 0x11, 0x34,
	0xd3, 0x8a, 0xdd, 0xf7, 0x9e, 0x9f, 0x46, 0x33, 0xcf, 0x00, 0x63, 0xf0, 0xdd, 0xad, 0x0f, 0x2e,
	0x3a, 0x9e, 0x21, 0xd7, 0x1f, 0x0c, 0xf2, 0xb5, 0x6f, 0xbb, 0x57, 0x1d, 0xf9, 0x39, 0xa4, 0x3b,
	0x6d, 0x05, 0xab, 0x58, 0x93, 0x4b, 0x44, 0x74, 0xba, 0x5e, 0x89, 0xe4, 0xe8, 0x74, 0xbd, 0x22,
	0xc7, 0x28, 0x91, 0x56, 0xac, 0x59, 0x48, 0x44, 0x7e, 0x06, 0x89, 0x75, 0x22, 0x23, 0x23, 0xb1,
	0x0e, 0x13, 0x41, 0x0f, 0x62, 0x52, 0xb1, 0xe6, 0x42, 0x22, 0x72, 0x0e, 0xd9, 0xd6, 0xa9, 0x51,
	0x40, 0xc5, 0x9a, 0xb9, 0x24, 0xe6, 0x57, 0x30, 0x75, 0x3e, 0x0e, 0x31, 0x88, 0xff, 0x15, 0x6b,
	0x0a, 0x79, 0x52, 0x27, 0x7f, 0x6b, 0xac, 0x98, 0x53, 0xfa, 0xa4, 0x70, 0x46, 0xaf, 0x63, 0x2b,
	0x16, 0x55, 0xda, 0x14, 0x92, 0xb8, 0x9e, 0xc1, 0x74, 0xad, 0x7b, 0x1f, 0xc7, 0xba, 0x80, 0x7c,
	0x6d, 0x5d, 0xd7, 0x06, 0x5d, 0x2f, 0x61, 0xf6, 0x6c, 0xcd, 0xfe, 0xc9, 0xf4, 0x9a, 0xdf, 0x40,
	0x11, 0x4d, 0xaf, 0x37, 0x6f, 0xd6, 0xec, 0xe9, 0x2c, 0x2e, 0x67, 0x68, 0x60, 0x80, 0x5f, 0x03,
	0xf1, 0x06, 0x77, 0x48, 0x68, 0x87, 0x1c, 0xf5, 0x2a, 0x86, 0x7a, 0x07, 0x60, 0xdb, 0x38, 0x3c,
	0xfa, 0x68, 0x9c, 0xc5, 0xa0, 0x0b, 0xe6, 0x65, 0x33, 0x18, 0x45, 0x43, 0xe6, 0x32, 0x47, 0xbd,
	0x32, 0xea, 0xef, 0x09, 0x2b, 0x49, 0xa8, 0x01, 0x7a, 0xba, 0x37, 0x8a, 0x5f, 0xc2, 0x24, 0x68,
	0xbf, 0x1b, 0xa9, 0xaa, 0x42, 0x1e, 0x05, 0x9e, 0xe1, 0xf0, 0xb8, 0xec, 0x58, 0x05, 0xf2, 0x92,
	0x7f, 0x1e, 0x4a, 0xf6, 0x75, 0x28, 0xd9, 0xf7, 0xa1, 0x64, 0xef, 0x3f, 0xe5, 0xbf, 0x87, 0x74,
	0x3b, 0xa5, 0x3f, 0xba, 0xfb, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x88, 0x06, 0xe1, 0xb1, 0x01,
	0x00, 0x00,
}
